# Generated by Django 5.0.6 on 2024-08-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_alter_sneaker_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='creator',
        ),
    ]
